name: Build-Push to Hub
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - name: login docker
       env:
         DOCKER_USER: ${{secrets.DOCKER_USERNAME}}
         DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
         TAG_NAME: $(date +%s)
       run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 
     - name: Build the Docker image
       env:
         DOCKER_USER: ${{secrets.DOCKER_USERNAME}}
         DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
         TAG_NAME: $(date +%s)
       run: docker build . --file Dockerfile --tag greenredblue/studentsaction:$TAG_NAME
     - name: Docker Push to Hub
       run: docker push $DOCKER_USER/studentsaction:$TAG_NAME
