name: Build-Push to Hub
on: [push]
# Env variable
env:
  DOCKER_USER: ${{secrets.DOCKER_USERNAME}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
  REPO_NAME: ${{secrets.REPO_NAME}}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - name: login docker
       env:
         TAG_NAME: $(date +%s)
       run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 
       
     - name: get the date for tag
       id: date
       run: echo "::set-output name=date::$(date +'%Y-%m-%d--%M-%S')"
     - name: Build the Docker image
       env:
         DOCKER_USER: ${{secrets.DOCKER_USERNAME}}
         DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
         TAG_NAME: $(date +%s)
     
       run: docker build . --file Dockerfile --tag $DOCKER_USER/$REPO_NAME:${{ steps.date.outputs.date }}
     - name: result of build
       run: echo "OK!"
     - name: Docker Push to Hub
       run: docker push $DOCKER_USER/$REPO_NAME:${{ steps.date.outputs.date }}
